[package]
name = "flazky-bird-lib"
version = "1.1.0"
edition = "2021"
publish = false

[dependencies]
alloy-primitives = {version = "0.8", features = ["serde"]}
alloy-sol-types = { version = "0.8" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
bincode = "1.3"